development:
  consumer_key: <%= ENV['TW_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TW_CONSUMER_SECRET'] %>

production:
  consumer_key: <%= ENV['TW_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TW_CONSUMER_SECRET'] %>

